<?php

namespace Pilote\TaskerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardRepository extends EntityRepository
{
	public function count()
	{
		return $this->createQueryBuilder('b')
					->select('count(b)')
					->getQuery()
					->getSingleScalarResult();
	}
}
