<?php

namespace Pilote\TaskerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HasCommentedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HasCommentedRepository extends EntityRepository
{
}
