<?php

namespace Pilote\TaskerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
	public function count()
	{
		return $this->createQueryBuilder('t')
					->select('count(t)')
					->getQuery()
					->getSingleScalarResult();
	}
}
