<?php

namespace Pilote\TaskerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TListRepository extends EntityRepository
{
}
