# Inclusion du fichier de routing du MainBundle
pilote_main:
    resource: "@PiloteMainBundle/Resources/config/routing.yml"
    prefix:   /

# Inclusion du fichier de routing du UserBundle
pilote_user:
    resource: "@PiloteUserBundle/Resources/config/routing.yml"
    prefix:   /profile

# Inclusion du fichier de routing du MessageBundle
pilote_message:
    resource: "@PiloteMessageBundle/Resources/config/routing.yml"
    prefix:   /messages

# Inclusion du fichier de routing du AdminBundle
pilote_admin:
    resource: "@PiloteAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

# Inclusion du fichier de routing du TaskerBundle
pilote_tasker:
    resource: "@PiloteTaskerBundle/Resources/config/routing.yml"
    prefix:   /

# Inclusion du fichier de routing du FOSUserBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Inclusion du fichier de routing du FOSJsRoutingBundle
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Inclusion du fichier de routing du FOSMessageBundle
#fos_message:
#    resource: "@FOSMessageBundle/Resources/config/routing.xml"
#    prefix: /message

