security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Pilote\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                #redirection pour que l'on aille sur /index après la connexion
                always_use_default_target_path : true
                default_target_path: /projets
            logout:
                path: fos_user_security_logout
                target: /
            remember_me:
                key: %secret%

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"


    access_control:
        - { path: ^/projets, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/profile/*, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/board/*, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/admin/*, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
