<?php

namespace PIL\TaskerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CheckListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckListRepository extends EntityRepository
{
}
