crud_board:
    pattern:  /
    defaults: { _controller: "PiloteTaskerBundle:Board:index" }

crud_board_show:
    pattern:  /{id}/show
    defaults: { _controller: "PiloteTaskerBundle:Board:show" }

crud_board_new:
    pattern:  /new
    defaults: { _controller: "PiloteTaskerBundle:Board:new" }

crud_board_create:
    pattern:  /create
    defaults: { _controller: "PiloteTaskerBundle:Board:create" }
    requirements: { _method: post }

crud_board_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PiloteTaskerBundle:Board:edit" }

crud_board_delete_check:
    pattern:  /{id}/delete_check
    defaults: { _controller: "PiloteTaskerBundle:Board:deleteCheck" }

crud_board_update:
    pattern:  /{id}/update
    defaults: { _controller: "PiloteTaskerBundle:Board:update" }
    requirements: { _method: post|put }

crud_board_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PiloteTaskerBundle:Board:delete" }
    requirements: { _method: post|delete }
