checklistoption:
    pattern:  /
    defaults: { _controller: "PiloteTaskerBundle:CheckListOption:index" }

checklistoption_show:
    pattern:  /{id}/show
    defaults: { _controller: "PiloteTaskerBundle:CheckListOption:show" }

checklistoption_new:
    pattern:  /new
    defaults: { _controller: "PiloteTaskerBundle:CheckListOption:new" }

checklistoption_create:
    pattern:  /create
    defaults: { _controller: "PiloteTaskerBundle:CheckListOption:create" }
    requirements: { _method: post }

checklistoption_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PiloteTaskerBundle:CheckListOption:edit" }

checklistoption_update:
    pattern:  /{id}/update
    defaults: { _controller: "PiloteTaskerBundle:CheckListOption:update" }
    requirements: { _method: post|put }

checklistoption_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PiloteTaskerBundle:CheckListOption:delete" }
    requirements: { _method: post|delete }
