crud_tlist:
    pattern:  /
    defaults: { _controller: "PiloteTaskerBundle:TList:index" }

crud_tlist_show:
    pattern:  /{id}/show
    defaults: { _controller: "PiloteTaskerBundle:TList:show" }

crud_tlist_new:
    pattern:  /new
    defaults: { _controller: "PiloteTaskerBundle:TList:new" }

crud_tlist_create:
    pattern:  /create
    defaults: { _controller: "PiloteTaskerBundle:TList:create" }
    requirements: { _method: post }

crud_tlist_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PiloteTaskerBundle:TList:edit" }

crud_tlist_update:
    pattern:  /{id}/update
    defaults: { _controller: "PiloteTaskerBundle:TList:update" }
    requirements: { _method: post|put }

crud_tlist_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PiloteTaskerBundle:TList:delete" }
    requirements: { _method: post|delete }
