piltasker_createTask:
    path: /createTask
    defaults: { _controller: PILTaskerBundle:Tasker:createTask }

piltasker_deleteTask:
    path: /deleteTask
    defaults: { _controller: PILTaskerBundle:Tasker:deleteTask }

piltasker_renameTask:
    path: /renameTask
    defaults: { _controller: PILTaskerBundle:Tasker:renameTask }

piltasker_getTaskDetails:
    path: /getTaskDetails
    defaults: { _controller: PILTaskerBundle:Tasker:getTaskDetails }

piltasker_updateTaskContent:
    path: /updateTaskContent
    defaults: { _controller: PILTaskerBundle:Tasker:updateTaskContent }

piltasker_createTList:
    path: /createTList
    defaults: { _controller: PILTaskerBundle:Tasker:createTList }

piltasker_deleteTList:
    path: /deleteTList
    defaults: { _controller: PILTaskerBundle:Tasker:deleteTList }

piltasker_renameTList:
    path: /renameTList
    defaults: { _controller: PILTaskerBundle:Tasker:renameTList }

piltasker_createStep:
    path: /createStep
    defaults: { _controller: PILTaskerBundle:Tasker:createStep }

piltasker_deleteStep:
    path: /deleteStep
    defaults: { _controller: PILTaskerBundle:Tasker:deleteStep }

piltasker_renameStep:
    path: /renameStep
    defaults: { _controller: PILTaskerBundle:Tasker:renameStep }

piltasker_createDomain:
    path: /createDomain
    defaults: { _controller: PILTaskerBundle:Tasker:createDomain }

piltasker_deleteDomain:
    path: /deleteDomain
    defaults: { _controller: PILTaskerBundle:Tasker:deleteDomain }

piltasker_renameDomain:
    path: /renameDomain
    defaults: { _controller: PILTaskerBundle:Tasker:renameDomain }

piltasker_createChecklist:
    path: /createChecklist
    defaults: { _controller: PILTaskerBundle:Tasker:createChecklist }

piltasker_renameChecklist:
    path: /renameChecklist
    defaults: { _controller: PILTaskerBundle:Tasker:renameChecklist }

piltasker_createChecklistOption:
    path: /createChecklistOption
    defaults: { _controller: PILTaskerBundle:Tasker:createChecklistOption }

piltasker_renameChecklistOption:
    path: /renameChecklistOption
    defaults: { _controller: PILTaskerBundle:Tasker:renameChecklistOption }

piltasker_createComment:
    path: /createComment
    defaults: { _controller: PILTaskerBundle:Tasker:createComment }
