# Copyright (C) 2015 Rémi Patrizio
# 
# ________________________________
# 
# This file is part of Pilote.
# 
#     Pilote is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     Pilote is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with Pilote.  If not, see <http://www.gnu.org/licenses/>.
#

pilote_message_index:
    pattern:  /
    defaults: { _controller: PiloteMessageBundle:Default:index }

pilote_message_thread:
    pattern:  /thread/{id}
    defaults: { _controller: PiloteMessageBundle:Default:thread }
    requirements:
        id: \d+

pilote_message_thread_leave:
    pattern:  /thread/{id}/leave
    defaults: { _controller: PiloteMessageBundle:Default:leaveThread }
    requirements:
        id: \d+

pilote_message_thread_close:
    pattern:  /thread/{id}/close
    defaults: { _controller: PiloteMessageBundle:Default:closeThread }
    requirements:
        id: \d+

pilote_message_adminThread:
    pattern:  /admin
    defaults: { _controller: PiloteMessageBundle:Default:adminThread }

pilote_message_newThread:
    pattern:  /newThread
    defaults: { _controller: PiloteMessageBundle:Default:newThread }

pilote_message_addParticipant:
    pattern:  /thread/{id}/addParticipant
    defaults: { _controller: PiloteMessageBundle:Default:addParticipant }
    requirements:
        id: \d+

pilote_message_ajax_message_request:
    resource: "ajaxMessageRequest.yml"
    prefix:   /messageRequest
    options:
        expose: true
    requirements:
        _method:  POST

pilote_message_newThread_searchUser:
    pattern:  /newThreadSearchUser
    defaults: { _controller: PiloteMessageBundle:Default:newThreadSearchUser }
    options:
        expose: true

pilote_message_addParticipant_searchUser:
    pattern:  /addParticipantSearchUser/{threadId}
    defaults: { _controller: PiloteMessageBundle:Default:addParticipantSearchUser }
    options:
        expose: true
    requirements:
        threadId: \d+

pilote_message_setAllRead:
    pattern:  /setAllRead
    defaults: { _controller: PiloteMessageBundle:Default:setAllRead }