pil_admin_homepage:
    pattern:  /
    defaults: { _controller: PILAdminBundle:Default:index }
    
pil_admin_users:
    pattern:  /users
    defaults: { _controller: PILAdminBundle:Default:users }
    
pil_admin_bdd:
    pattern:  /bdd
    defaults: { _controller: PILAdminBundle:Default:bdd }
    
pil_admin_stats:
    pattern:  /stats
    defaults: { _controller: PILAdminBundle:Default:stats }
    
pil_admin_activity:
    pattern:  /activity
    defaults: { _controller: PILAdminBundle:Default:activity }

