<?php

namespace Pilote\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
	public function findLastFives($user)
    {
        $query = $this->createQueryBuilder('n')
        	->select('n')
        	->where('n.receiver = :user')
	        ->orderBy('n.date', 'DESC')
	        ->setParameter('user', $user)
	        ->setMaxResults(5);
        return $query->getQuery()->getResult();
	}

	public function findNextFives($notif, $user)
    {
        $query = $this->createQueryBuilder('n')
        	->select('n')
        	->where('n.receiver = :user')
        	->andWhere('n.date < :date')
	        ->orderBy('n.date', 'DESC')
	        ->setParameter('date', $notif->getDate())
	        ->setParameter('user', $user)
	        ->setMaxResults(5);
        return $query->getQuery()->getResult();
	}
}
