pilote_profil_show:
    pattern: /
    defaults: { _controller: PiloteUserBundle:Profile:show}

pilote_profil_showAnotherProfile:
    pattern:  /id-{id}
    defaults: { _controller: PiloteUserBundle:Profile:show}
    options:
        expose: true

pilote_profil_edit:
    pattern:  /edit
    defaults: { _controller: PiloteUserBundle:Profile:edit }

pilote_profil_picture_new:
    pattern:  /picture/new
    defaults: { _controller: PiloteUserBundle:Profile:checkNewPicture }

pilote_profil_picture_checkEdit:
    pattern:  /picture/checkEdit
    defaults: { _controller: PiloteUserBundle:Profile:checkEditPicture }

pilote_profil_picture_delete:
    pattern:  /picture/delete
    defaults: { _controller: PiloteUserBundle:Profile:deletePicture }