# Copyright (C) 2015 Rémi Patrizio
# 
# ________________________________
# 
# This file is part of Pilote.
# 
#     Pilote is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     Pilote is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with Pilote.  If not, see <http://www.gnu.org/licenses/>.
#

####################################################################
# Fichier de routes des requêtes AJAX communes à toutes les pages. #
# Pour l'instant, il ne s'agit que des requêtes concernant le      #
# système de notifications                                         #
####################################################################

###################################
# Requêtes AJAX des notifications #
###################################

pilote_main_loadNextNotifications:
    path: /loadNextNotifications
    defaults: { _controller: PiloteMainBundle:Ajax:loadNextNotifications }

pilote_main_removeAllNotifications:
    path: /removeAllNotifications
    defaults: { _controller: PiloteMainBundle:Ajax:removeAllNotifications }

pilote_main_removeNotification:
    path: /removeNotification
    defaults: { _controller: PiloteMainBundle:Ajax:removeNotification }

pilote_main_notificationsRead:
    path: /notificationsRead
    defaults: { _controller: PiloteMainBundle:Ajax:setAllNotificationsRead }