parameters:
#    pil_tasker.example.class: PIL\TaskerBundle\Example

services:
#    pil_tasker.example:
#        class: %pil_tasker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
